# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- master

pool:
  vmImage: 'windows-2019'

resources:
  repositories:
  - repository: authentication
    type: github
    name: Azure-Devops-PowerShell-Module/authentication
    endpoint: Azure-Devops-PowerShell-Module
    ref: refs/tags/$(Tag)
  - repository: operations
    type: github
    name: Azure-Devops-PowerShell-Module/operations
    endpoint: Azure-Devops-PowerShell-Module
    ref: refs/tags/$(Tag)
  - repository: processes
    type: github
    name: Azure-Devops-PowerShell-Module/processes
    endpoint: Azure-Devops-PowerShell-Module
    ref: refs/tags/$(Tag)
  - repository: projects
    type: github
    name: Azure-Devops-PowerShell-Module/projects
    endpoint: Azure-Devops-PowerShell-Module
    ref: refs/tags/$(Tag)
  - repository: teams
    type: github
    name: Azure-Devops-PowerShell-Module/teams
    endpoint: Azure-Devops-PowerShell-Module
    ref: refs/tags/$(Tag)

stages:
  - stage: Build
    jobs:
    - job: SetupNestedModules
      displayName: Setup Nested Modules
      timeoutInMinutes: 0
      steps:
      - checkout: self
        submodules: true
        persistCredentials: true
      - checkout: authentication
      - checkout: operations
      - checkout: processes
      - checkout: projects
      - checkout: teams
      - powershell: | 
          git clone https://github.com/Azure-Devops-PowerShell-Module/AzDevOps.git Staging
          Set-Location .\Staging
          git branch $(Tag) 
        displayName: Git Switch Branch
        name: GitSwitchBRanch
        workingDirectory: $(build.sourcesDirectory)
        failOnStderr: true
      - powershell: | 
          Install-Module -Name psake -Scope CurrentUser -SkipPublisherCheck -Force
          Import-Module psake
        displayName: Install psake Module
        name: InstallPsake
        workingDirectory: $(build.sourcesDirectory)
        failOnStderr: true
      - powershell: | 
          New-Item .\Staging\authentication -Itemtype Directory 
          New-Item .\Staging\authentication\en-us -Itemtype Directory
          Copy-Item .\authentication\authentication.* .\Staging\authentication
          Copy-Item .\authentication\docs\en-us\* .\Staging\authentication\en-us
        displayName: Authentication File Copy
        name: AuthenticationFileCopy
        workingDirectory: $(build.sourcesDirectory)
        failOnStderr: true
      - powershell: |
          New-Item .\Staging\operations -Itemtype Directory 
          New-Item .\Staging\operations\en-us -Itemtype Directory
          Copy-Item .\operations\operations.* .\Staging\operations
          Copy-Item .\operations\docs\en-us\* .\Staging\operations\en-us
        displayName: Operations File Copy
        name: OperationsFileCopy
        workingDirectory: $(build.sourcesDirectory)
        failOnStderr: true
      - powershell: |
          New-Item .\Staging\processes -Itemtype Directory 
          New-Item .\Staging\processes\en-us -Itemtype Directory
          Copy-Item .\processes\processes.* .\Staging\processes
          Copy-Item .\processes\docs\en-us\* .\Staging\processes\en-us
        displayName: Processes File Copy
        name: ProcessesFileCopy
        workingDirectory: $(build.sourcesDirectory)
        failOnStderr: true
      - powershell: |
          New-Item .\Staging\projects -Itemtype Directory 
          New-Item .\Staging\projects\en-us -Itemtype Directory
          Copy-Item .\projects\projects.* .\Staging\projects
          Copy-Item .\projects\docs\en-us\* .\Staging\projects\en-us
        displayName: File Projects Copy
        name: ProjectsFileCopy
        workingDirectory: $(build.sourcesDirectory)
        failOnStderr: true
      - powershell: |
          New-Item .\Staging\teams -Itemtype Directory 
          New-Item .\Staging\teams\en-us -Itemtype Directory
          Copy-Item .\teams\teams.* .\Staging\teams
          Copy-Item .\teams\docs\en-us\* .\Staging\teams\en-us
          Get-ChildItem .\Staging -Recurse
        displayName: File Teams Copy
        name: TeamsFileCopy
        workingDirectory: $(build.sourcesDirectory)
        failOnStderr: true
      - powershell: | 
          Set-Location .\Staging
          git status
        displayName: Git Status Check
        name: GitStatusCheck
        workingDirectory: $(build.sourcesDirectory)
        failOnStderr: true