# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- master

pool:
  vmImage: 'windows-2019'

resources:
  repositories:
  - repository: authentication
    type: github
    name: Azure-Devops-PowerShell-Module/authentication
    endpoint: Azure-Devops-PowerShell-Module
    ref: refs/tags/$(Tag)
  - repository: operations
    type: github
    name: Azure-Devops-PowerShell-Module/operations
    endpoint: Azure-Devops-PowerShell-Module
    ref: refs/tags/$(Tag)
  - repository: processes
    type: github
    name: Azure-Devops-PowerShell-Module/processes
    endpoint: Azure-Devops-PowerShell-Module
    ref: refs/tags/$(Tag)
  - repository: projects
    type: github
    name: Azure-Devops-PowerShell-Module/projects
    endpoint: Azure-Devops-PowerShell-Module
    ref: refs/tags/$(Tag)
  - repository: teams
    type: github
    name: Azure-Devops-PowerShell-Module/teams
    endpoint: Azure-Devops-PowerShell-Module
    ref: refs/tags/$(Tag)

stages:
  - stage: Build
    jobs:
    - job: SetupAuthentication
      displayName: Setup Authentication Module
      timeoutInMinutes: 0
      steps:
      - checkout: self
      - checkout: authentication
      - powershell: | 
          New-Item .\AzDevOps\authentication -Itemtype Directory 
          New-Item .\AzDevOps\authentication\en-us -Itemtype Directory
          Copy-Item .\authentication\authentication.* .\AzDevOps\authentication
          Copy-Item .\authentication\docs\en-us\* .\AzDevOps\authentication\en-us
          Get-ChildItem .\AzDevOps -Recurse
        displayName: Say hello
        name: firstStep
        workingDirectory: $(build.sourcesDirectory)
        failOnStderr: true
        env:
          name: Microsoft