# Trigger the workflow on milestone events
on:
  milestone:
    types: [closed]
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'
        required: true
        default: '1'
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action
        env:
          GITHUB_TOKEN: ${{ secrets.release_notes_pat }}
          OUTPUT_FOLDER: temp_release_notes
          FILENAME: ReleaseNotes.md
          USE_MILESTONE_TITLE: "true"